# Generated by Django 5.1.4 on 2025-07-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='app_name',
            field=models.CharField(default='hokm', max_length=255, verbose_name='App Name'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='game_package_name',
            field=models.CharField(default='hokm', max_length=255, verbose_name='Game Package Name'),
        ),
    ]
