# Generated by Django 5.2.4 on 2025-08-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, editable=False, verbose_name='Score')),
            ],
        ),
        migrations.CreateModel(
            name='LeaderboardReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_rank', models.IntegerField(default=1, verbose_name='From Rank')),
                ('to_rank', models.IntegerField(default=10, verbose_name='To Rank')),
            ],
            options={
                'verbose_name': 'Leaderboard Reward',
                'verbose_name_plural': 'Leaderboard Rewards',
            },
        ),
        migrations.CreateModel(
            name='LeaderboardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('duration', models.DurationField(blank=True, default='1 00:00:00', help_text='If set to null, it means infinite.', null=True, verbose_name='Duration')),
                ('start_time', models.DateTimeField(verbose_name='Start time')),
            ],
            options={
                'verbose_name': 'Leaderboard Type',
                'verbose_name_plural': 'Leaderboard Types',
                'ordering': ('-duration', 'name'),
            },
        ),
    ]
