# Generated by Django 5.2.4 on 2025-08-14 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leaderboard', '0001_initial'),
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard', to=settings.AUTH_USER_MODEL, verbose_name='Player'),
        ),
        migrations.AddField(
            model_name='leaderboardreward',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.rewardpackage', verbose_name='Reward'),
        ),
        migrations.AddField(
            model_name='leaderboardreward',
            name='leaderboard_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='leaderboard.leaderboardtype', verbose_name='Leaderboard Type'),
        ),
    ]
