# Generated by Django 5.1.4 on 2025-07-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_alter_leaderboard_player'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboardtype',
            options={'ordering': ('-duration', 'name'), 'verbose_name': 'Leaderboard Type', 'verbose_name_plural': 'Leaderboard Types'},
        ),
    ]
