# Generated by Django 5.2.4 on 2025-08-14 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewardpackage',
            name='support_type',
        ),
        migrations.RemoveField(
            model_name='rewardpackage',
            name='vip',
        ),
        migrations.RemoveField(
            model_name='rewardpackage',
            name='vip_duration',
        ),
        migrations.RemoveField(
            model_name='shoppackage',
            name='support_type',
        ),
        migrations.RemoveField(
            model_name='shoppackage',
            name='vip',
        ),
        migrations.RemoveField(
            model_name='shoppackage',
            name='vip_duration',
        ),
    ]
