# Generated by Django 5.1.4 on 2025-01-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardpackage',
            name='claimable',
            field=models.BooleanField(default=False, verbose_name='Claimable'),
        ),
    ]
