# Generated by Django 5.1.4 on 2025-01-12 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rewardpackage_claimable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppackage',
            options={'ordering': ('priority',), 'verbose_name': 'Shop Package', 'verbose_name_plural': 'Shop Packages'},
        ),
    ]
