# Generated by Django 5.1.4 on 2025-01-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_shoppackage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardpackage',
            name='support_type',
            field=models.CharField(choices=[('none', 'None'), ('purchase', 'Purchase'), ('honorary', 'Honorary'), ('reward', 'Reward')], default='none', max_length=100, verbose_name='Support Type'),
        ),
        migrations.AddField(
            model_name='rewardpackage',
            name='vip',
            field=models.BooleanField(default=False, verbose_name='VIP'),
        ),
        migrations.AddField(
            model_name='rewardpackage',
            name='vip_duration',
            field=models.DurationField(blank=True, null=True, verbose_name='VIP Duration'),
        ),
        migrations.AddField(
            model_name='shoppackage',
            name='support_type',
            field=models.CharField(choices=[('none', 'None'), ('purchase', 'Purchase'), ('honorary', 'Honorary'), ('reward', 'Reward')], default='none', max_length=100, verbose_name='Support Type'),
        ),
        migrations.AddField(
            model_name='shoppackage',
            name='vip',
            field=models.BooleanField(default=False, verbose_name='VIP'),
        ),
        migrations.AddField(
            model_name='shoppackage',
            name='vip_duration',
            field=models.DurationField(blank=True, null=True, verbose_name='VIP Duration'),
        ),
    ]
