# Generated by Django 5.1.4 on 2025-01-17 15:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_dailyrewardpackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LuckyWheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('name', models.CharField(default='Wheel of fortune', max_length=255, verbose_name='Name')),
                ('cool_down', models.DurationField(default=datetime.timedelta(days=1), verbose_name='Cool down')),
            ],
            options={
                'verbose_name': 'Lucky Wheel',
                'verbose_name_plural': 'Lucky Wheel',
            },
        ),
        migrations.CreateModel(
            name='LuckyWheelSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('chance', models.PositiveIntegerField(default=0, verbose_name='Chance')),
                ('lucky_wheel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='shop.luckywheel', verbose_name='Lucky Wheel')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.rewardpackage', verbose_name='Package')),
            ],
            options={
                'verbose_name': 'Lucky Wheel Section',
                'verbose_name_plural': 'Lucky Wheel Sections',
                'unique_together': {('package', 'lucky_wheel')},
            },
        ),
    ]
