# Generated by Django 5.1.4 on 2025-01-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_luckywheel_luckywheelsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardpackage',
            name='reward_type',
            field=models.CharField(choices=[('initial_wallet', 'Initial'), ('daily', 'Daily'), ('lucky_wheel', 'Lucky Wheel')], max_length=50, verbose_name='Reward Type'),
        ),
    ]
