# Generated by Django 5.1.4 on 2025-05-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_rewardpackage_reward_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardpackage',
            name='reward_type',
            field=models.CharField(choices=[('initial_wallet', 'Initial'), ('daily', 'Daily'), ('lucky_wheel', 'Lucky Wheel'), ('match_reward', 'Match Reward')], max_length=50, verbose_name='Reward Type'),
        ),
    ]
