# Generated by Django 5.1.4 on 2025-05-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_rewardpackage_reward_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppackage',
            name='price_amount',
            field=models.FloatField(default=0.0, verbose_name='Price Amount'),
        ),
    ]
