# Generated by Django 5.2.4 on 2025-07-13 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_rewardpackage_reward_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopconfiguration',
            name='player_initial_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.rewardpackage', verbose_name='Player Initial Package'),
        ),
    ]
