# Generated by Django 5.2.4 on 2025-07-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_shopconfiguration_player_initial_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardpackage',
            name='priority',
            field=models.PositiveIntegerField(default=1, help_text='1 is More important', verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='shoppackage',
            name='priority',
            field=models.PositiveIntegerField(default=1, help_text='1 is More important', verbose_name='Priority'),
        ),
    ]
