# Generated by Django 5.2.4 on 2025-07-13 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_rewardpackage_priority_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='market',
            options={'ordering': ['created_time'], 'verbose_name': 'Market', 'verbose_name_plural': 'Markets'},
        ),
    ]
