# Generated by Django 5.1.4 on 2025-01-12 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0002_rewardpackage_claimable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Amount')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.currency', verbose_name='Currency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerShopInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('assets', models.ManyToManyField(blank=True, to='shop.asset', verbose_name='Assets')),
                ('currencies', models.ManyToManyField(blank=True, to='player_shop.playercurrency', verbose_name='Player Currencies')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='shop_info', to=settings.AUTH_USER_MODEL, verbose_name='Player')),
                ('player_market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.market', verbose_name='Market')),
            ],
            options={
                'verbose_name': 'Player Shop Info',
                'verbose_name_plural': 'Players Shop Info',
            },
        ),
        migrations.CreateModel(
            name='PlayerWalletLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('transaction_type', models.CharField(choices=[('spend', 'Spend'), ('earn', 'Earn')], default='earn', max_length=10)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Transaction ID')),
                ('amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Amount')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.asset', verbose_name='Asset')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.currency', verbose_name='Currency')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Player')),
            ],
            options={
                'verbose_name': 'Player Wallet Log',
                'verbose_name_plural': 'Player Wallet Logs',
            },
        ),
    ]
