# Generated by Django 5.2.4 on 2025-08-14 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
            ],
            options={
                'verbose_name': 'Player Wallet',
                'verbose_name_plural': 'Players Wallets',
            },
        ),
        migrations.CreateModel(
            name='PlayerWalletLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('transaction_type', models.CharField(choices=[('spend', 'Spend'), ('earn', 'Earn')], default='earn', max_length=10)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Transaction ID')),
                ('amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Amount')),
            ],
            options={
                'verbose_name': 'Player Wallet Log',
                'verbose_name_plural': 'Player Wallet Logs',
            },
        ),
        migrations.CreateModel(
            name='AssetOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField(default=False, verbose_name='Is Current')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.asset', verbose_name='Asset')),
            ],
            options={
                'verbose_name': 'Asset Ownership',
                'verbose_name_plural': 'Asset Ownerships',
            },
        ),
        migrations.CreateModel(
            name='CurrencyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.currency')),
            ],
            options={
                'verbose_name': 'Currency Balance',
                'verbose_name_plural': 'Currency Balance',
            },
        ),
        migrations.CreateModel(
            name='PlayerRewardPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.rewardpackage', verbose_name='Reward Package')),
            ],
            options={
                'verbose_name': 'Player Reward Package',
                'verbose_name_plural': 'Player Reward Packages',
            },
        ),
    ]
