# Generated by Django 5.2.4 on 2025-08-14 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player_shop', '0001_initial'),
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playerrewardpackage',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Player'),
        ),
        migrations.AddField(
            model_name='playerwallet',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='shop_info', to=settings.AUTH_USER_MODEL, verbose_name='Player'),
        ),
        migrations.AddField(
            model_name='playerwallet',
            name='player_market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.market', verbose_name='Market'),
        ),
        migrations.AddField(
            model_name='currencybalance',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_balances', to='player_shop.playerwallet'),
        ),
        migrations.AddField(
            model_name='assetownership',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_ownerships', to='player_shop.playerwallet'),
        ),
        migrations.AddField(
            model_name='playerwalletlog',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.asset', verbose_name='Asset'),
        ),
        migrations.AddField(
            model_name='playerwalletlog',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='playerwalletlog',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Player'),
        ),
        migrations.AlterUniqueTogether(
            name='currencybalance',
            unique_together={('wallet', 'currency')},
        ),
        migrations.AlterUniqueTogether(
            name='assetownership',
            unique_together={('wallet', 'asset')},
        ),
    ]
