# Generated by Django 5.1.4 on 2025-01-14 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_shop', '0001_initial'),
        ('shop', '0004_rewardpackage_support_type_rewardpackage_vip_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playershopinfo',
            name='currencies',
        ),
        migrations.RemoveField(
            model_name='playershopinfo',
            name='assets',
        ),
        migrations.RemoveField(
            model_name='playershopinfo',
            name='player',
        ),
        migrations.RemoveField(
            model_name='playershopinfo',
            name='player_market',
        ),
        migrations.CreateModel(
            name='PlayerWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='shop_info', to=settings.AUTH_USER_MODEL, verbose_name='Player')),
                ('player_market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.market', verbose_name='Market')),
            ],
            options={
                'verbose_name': 'Player Shop Info',
                'verbose_name_plural': 'Players Shop Info',
            },
        ),
        migrations.CreateModel(
            name='CurrencyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.currency')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_balances', to='player_shop.playerwallet')),
            ],
            options={
                'unique_together': {('wallet', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='AssetOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.asset')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_ownerships', to='player_shop.playerwallet')),
            ],
            options={
                'unique_together': {('wallet', 'asset')},
            },
        ),
        migrations.DeleteModel(
            name='PlayerCurrency',
        ),
        migrations.DeleteModel(
            name='PlayerShopInfo',
        ),
    ]
