# Generated by Django 5.1.4 on 2025-01-15 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_shop', '0002_remove_playershopinfo_currencies_and_more'),
        ('shop', '0004_rewardpackage_support_type_rewardpackage_vip_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetownership',
            options={'verbose_name': 'Asset Ownership', 'verbose_name_plural': 'Asset Ownerships'},
        ),
        migrations.AlterModelOptions(
            name='currencybalance',
            options={'verbose_name': 'Currency Balance', 'verbose_name_plural': 'Currency Balance'},
        ),
        migrations.AlterModelOptions(
            name='playerwallet',
            options={'verbose_name': 'Player Wallet', 'verbose_name_plural': 'Players Wallets'},
        ),
        migrations.AlterField(
            model_name='assetownership',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.asset', verbose_name='Asset'),
        ),
    ]
