# Generated by Django 5.1.4 on 2025-01-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_shop', '0004_playerrewardpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetownership',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='Is Current'),
        ),
    ]
