# Generated by Django 5.2.4 on 2025-07-20 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_friendshiprequest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendship',
            options={'ordering': ('-created_time',), 'verbose_name': 'Friendship', 'verbose_name_plural': 'Friendships'},
        ),
    ]
