# Generated by Django 5.1.4 on 2025-01-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalplayer',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Is verified'),
        ),
    ]
