# Generated by Django 5.1.4 on 2025-01-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_normalplayer_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestplayer',
            name='recovery_string',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Recovery string'),
        ),
    ]
