# Generated by Django 5.2.4 on 2025-08-29 15:31

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_populate_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),
        ),
    ]
