# Generated by Django 5.1.4 on 2025-01-14 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_guestplayer_recovery_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupporterPlayerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('visible', models.BooleanField(default=False, verbose_name='Is visible')),
                ('used', models.BooleanField(default=False, verbose_name='Is used')),
                ('reason', models.CharField(max_length=10, verbose_name='Reason')),
                ('approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='Approval date')),
                ('message', models.CharField(blank=True, max_length=100, null=True, verbose_name='Message')),
                ('instagram_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram')),
                ('telegram_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram')),
                ('rubika_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rubika')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supports', to=settings.AUTH_USER_MODEL, verbose_name='Player')),
            ],
            options={
                'verbose_name': 'Player Support info',
                'verbose_name_plural': 'Player Support info',
                'ordering': ('-created_time',),
            },
        ),
        migrations.CreateModel(
            name='VipPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('expiration_date', models.DateTimeField(verbose_name='Expiration date')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vip', to=settings.AUTH_USER_MODEL, verbose_name='Player')),
            ],
            options={
                'verbose_name': 'VIP player',
                'verbose_name_plural': 'VIP players',
            },
        ),
    ]
