# Generated by Django 5.1.4 on 2025-01-16 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_deviceidblacklist_alter_vipplayer_expiration_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceIdBlackList',
        ),
    ]
