# Generated by Django 5.1.4 on 2025-01-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_delete_deviceidblacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestplayer',
            name='daily_reward_streak',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Daily reward streak'),
        ),
        migrations.AddField(
            model_name='guestplayer',
            name='last_claimed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last claimed'),
        ),
        migrations.AddField(
            model_name='normalplayer',
            name='daily_reward_streak',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Daily reward streak'),
        ),
        migrations.AddField(
            model_name='normalplayer',
            name='last_claimed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last claimed'),
        ),
    ]
