# Generated by Django 5.1.4 on 2025-01-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_guestplayer_daily_reward_streak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestplayer',
            name='last_lucky_wheel_spin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last lucky wheel spin.'),
        ),
        migrations.AddField(
            model_name='normalplayer',
            name='last_lucky_wheel_spin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last lucky wheel spin.'),
        ),
    ]
