# Generated by Django 5.1.4 on 2025-01-20 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_guestplayer_last_lucky_wheel_spin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='inviter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites', to=settings.AUTH_USER_MODEL, verbose_name='Inviter'),
        ),
    ]
