# Generated by Django 5.1.4 on 2025-01-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_guestplayer_birth_date_remove_guestplayer_cup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestplayer',
            name='daily_reward_streak',
        ),
        migrations.RemoveField(
            model_name='guestplayer',
            name='last_claimed',
        ),
        migrations.RemoveField(
            model_name='guestplayer',
            name='last_lucky_wheel_spin',
        ),
        migrations.RemoveField(
            model_name='normalplayer',
            name='daily_reward_streak',
        ),
        migrations.RemoveField(
            model_name='normalplayer',
            name='last_claimed',
        ),
        migrations.RemoveField(
            model_name='normalplayer',
            name='last_lucky_wheel_spin',
        ),
        migrations.AddField(
            model_name='user',
            name='daily_reward_streak',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Daily reward streak'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_claimed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last claimed'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_lucky_wheel_spin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last lucky wheel spin.'),
        ),
    ]
