# Generated by Django 5.1.4 on 2025-01-24 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_guestplayer_daily_reward_streak_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cup',
        ),
        migrations.RemoveField(
            model_name='user',
            name='score',
        ),
        migrations.RemoveField(
            model_name='user',
            name='xp',
        ),
    ]
