# Generated by Django 5.1.4 on 2025-01-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_user_cup_remove_user_score_remove_user_xp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestplayer',
            name='profile_name',
        ),
        migrations.RemoveField(
            model_name='normalplayer',
            name='profile_name',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Profile name'),
        ),
    ]
