# Generated by Django 5.1.4 on 2025-05-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_guestplayer_profile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='block_reliefe_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Block reliefe'),
        ),
    ]
