# Generated by Django 5.2.4 on 2025-08-14 12:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'ordering': ('-created_time',),
            },
        ),
        migrations.CreateModel(
            name='MatchConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('simultaneous_game', models.BooleanField(default=False, verbose_name='Simultaneous availability')),
            ],
            options={
                'verbose_name': 'Match Configuration',
                'verbose_name_plural': 'Match Configuration',
            },
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('match_uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('history', models.JSONField(default=dict, verbose_name='History')),
            ],
            options={
                'verbose_name': 'Match Result',
                'verbose_name_plural': 'Match Results',
            },
        ),
        migrations.CreateModel(
            name='MatchType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('priority', models.PositiveSmallIntegerField(default=1, verbose_name='Priority')),
                ('min_xp', models.PositiveSmallIntegerField(default=0, verbose_name='Min XP')),
                ('min_cup', models.PositiveSmallIntegerField(default=0, verbose_name='Min Cup')),
                ('min_score', models.PositiveSmallIntegerField(default=0, verbose_name='Min Score')),
                ('config', models.JSONField(default=dict, verbose_name='Config')),
                ('winner_xp', models.PositiveSmallIntegerField(default=0, verbose_name='Winner XP')),
                ('winner_cup', models.PositiveSmallIntegerField(default=0, verbose_name='Winner Cup')),
                ('winner_score', models.PositiveSmallIntegerField(default=0, verbose_name='Winner Score')),
                ('loser_xp', models.PositiveSmallIntegerField(default=0, verbose_name='Loser XP')),
                ('loser_cup', models.PositiveSmallIntegerField(default=0, verbose_name='Loser Cup')),
                ('loser_score', models.PositiveSmallIntegerField(default=0, verbose_name='Loser Score')),
                ('mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=15)),
            ],
            options={
                'verbose_name': 'Match Type',
                'verbose_name_plural': 'Match Types',
                'ordering': ('priority', 'name'),
            },
        ),
    ]
