# Generated by Django 5.1.4 on 2025-05-04 14:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('match_uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('history', models.JSONField(default=dict, verbose_name='History')),
                ('match_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_results', to='match.matchtype', verbose_name='Match Type')),
                ('players', models.ManyToManyField(blank=True, related_name='game_results', to=settings.AUTH_USER_MODEL, verbose_name='Players')),
            ],
            options={
                'verbose_name': 'Match Result',
                'verbose_name_plural': 'Match Results',
            },
        ),
    ]
