# Generated by Django 5.2.4 on 2025-07-15 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ('-created_time',), 'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
    ]
