# Generated by Django 5.2.4 on 2025-08-14 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('match', '0001_initial'),
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Players'),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='game_results', to=settings.AUTH_USER_MODEL, verbose_name='Players'),
        ),
        migrations.AddField(
            model_name='matchtype',
            name='entry_cost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.cost', verbose_name='Entry cost'),
        ),
        migrations.AddField(
            model_name='matchtype',
            name='loser_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_type_loser_packages', to='shop.rewardpackage', verbose_name='Loser package'),
        ),
        migrations.AddField(
            model_name='matchtype',
            name='winner_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_type_winner_packages', to='shop.rewardpackage', verbose_name='Winner package'),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='match_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_results', to='match.matchtype', verbose_name='Match Type'),
        ),
        migrations.AddField(
            model_name='match',
            name='match_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='match.matchtype', verbose_name='Match Type'),
        ),
    ]
