# Generated by Django 5.2.4 on 2025-08-14 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='owner',
        ),
    ]
