# Generated by Django 5.2.4 on 2025-07-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_alter_match_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchtype',
            name='mode',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=15),
        ),
    ]
