# Generated by Django 5.2.4 on 2025-08-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_remove_match_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchtype',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='match/type/banner', verbose_name='Banner'),
        ),
    ]
