# Generated by Django 5.2.4 on 2025-08-18 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_matchtype_banner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matchtype',
            name='matchmaking_timeout',
            field=models.PositiveIntegerField(default=300, help_text='How long to wait for matchmaking before timeout', verbose_name='Matchmaking Timeout (seconds)'),
        ),
        migrations.AddField(
            model_name='matchtype',
            name='max_players',
            field=models.PositiveSmallIntegerField(default=2, help_text='Maximum number of players for this match type', verbose_name='Max Players'),
        ),
        migrations.AddField(
            model_name='matchtype',
            name='min_players',
            field=models.PositiveSmallIntegerField(default=2, help_text='Minimum number of players for this match type', verbose_name='Min Players'),
        ),
        migrations.AddField(
            model_name='matchtype',
            name='pool_name',
            field=models.CharField(default='default_pool', help_text='OpenMatch pool name for this match type', max_length=100, verbose_name='Pool Name'),
        ),
        migrations.AddField(
            model_name='matchtype',
            name='search_fields_config',
            field=models.JSONField(default=dict, help_text='Configuration for OpenMatch search fields', verbose_name='Search Fields Config'),
        ),
        migrations.CreateModel(
            name='MatchmakingTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('ticket_id', models.CharField(max_length=255, unique=True, verbose_name='Ticket ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('cancelled', 'Cancelled'), ('error', 'Error')], default='pending', max_length=20, verbose_name='Status')),
                ('search_fields', models.JSONField(default=dict, help_text='OpenMatch search fields for this ticket', verbose_name='Search Fields')),
                ('assignment', models.JSONField(blank=True, default=dict, help_text='Match assignment data from OpenMatch', verbose_name='Assignment')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('match_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchmaking_tickets', to='match.matchtype', verbose_name='Match Type')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchmaking_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Player')),
            ],
            options={
                'verbose_name': 'Matchmaking Ticket',
                'verbose_name_plural': 'Matchmaking Tickets',
                'indexes': [models.Index(fields=['ticket_id'], name='match_match_ticket__11d6a8_idx'), models.Index(fields=['player', 'status'], name='match_match_player__a848f1_idx'), models.Index(fields=['match_type', 'status'], name='match_match_match_t_eb57ff_idx')],
                'unique_together': {('player', 'match_type', 'status')},
            },
        ),
    ]
