# Generated by Django 5.2.4 on 2025-08-18 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_matchtype_matchmaking_timeout_matchtype_max_players_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='matchmakingticket',
            name='match_match_ticket__11d6a8_idx',
        ),
        migrations.RemoveIndex(
            model_name='matchmakingticket',
            name='match_match_player__a848f1_idx',
        ),
        migrations.RemoveIndex(
            model_name='matchmakingticket',
            name='match_match_match_t_eb57ff_idx',
        ),
        migrations.AlterUniqueTogether(
            name='matchmakingticket',
            unique_together=set(),
        ),
    ]
