codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 75%
        threshold: 1%
        if_ci_failed: error
    patch:
      default:
        target: 80%
        threshold: 1%

ignore:
  - "*/migrations/*"
  - "*/venv/*"
  - "*/env/*"
  - "manage.py"
  - "*/settings.py"
  - "*/wsgi.py"
  - "*/asgi.py"
  - "*/tests/*"
  - "*/test_*.py"
  - "*/__init__.py"
  - "*/locale/*"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
